server:
  port: 48090
spring:
  application:
    name: openapi-server
  profiles:
    active: local
  threads:
    virtual:
      enabled: true
  config:
    import:
      - optional:classpath:application-${spring.profiles.active}.yaml # 加载【本地】配置
