CREATE TABLE IF NOT EXISTS "route_db_harness_smoke" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(64)
);

CREATE TABLE IF NOT EXISTS "route_config" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "route_code" varchar(32) NOT NULL,
    "name" varchar(128) NOT NULL,
    "product_code" varchar(32) NOT NULL,
    "org_id" bigint DEFAULT NULL,
    "target_type" varchar(16) NOT NULL DEFAULT 'SINGLE',
    "target_ds_interface_id" bigint DEFAULT NULL,
    "priority" int NOT NULL DEFAULT 0,
    "status" tinyint NOT NULL DEFAULT 0,
    "remark" varchar(512) DEFAULT '',
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_route_config_code" UNIQUE ("route_code")
) COMMENT '路由配置表';
