--- #################### 注册中心相关配置 ####################

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
        namespace: dev # 命名空间，与 yudao-gateway 保持一致，便于服务发现互通

--- #################### 数据库相关配置 ####################

spring:
  datasource:
    dynamic: # 多数据源配置
      primary: master
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/apiten_route?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true
          username: root
          password: apiten123
