CREATE TABLE IF NOT EXISTS "org_db_harness_smoke" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(64)
);

CREATE TABLE IF NOT EXISTS "org_info" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "org_code" varchar(32) NOT NULL,
    "name" varchar(128) NOT NULL,
    "unified_social_credit_code" varchar(32) DEFAULT '',
    "contact_person" varchar(64) DEFAULT '',
    "contact_phone" varchar(32) DEFAULT '',
    "status" tinyint NOT NULL DEFAULT 0,
    "business_owner" varchar(64) DEFAULT '',
    "remark" varchar(512) DEFAULT '',
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_org_info_code" UNIQUE ("org_code")
) COMMENT '机构信息表';
