CREATE TABLE IF NOT EXISTS "org_db_harness_smoke" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(64)
);

CREATE TABLE IF NOT EXISTS "org_info" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "org_code" varchar(32) NOT NULL,
    "name" varchar(128) NOT NULL,
    "unified_social_credit_code" varchar(32) DEFAULT '',
    "contact_person" varchar(64) DEFAULT '',
    "contact_phone" varchar(32) DEFAULT '',
    "status" tinyint NOT NULL DEFAULT 0,
    "business_owner" varchar(64) DEFAULT '',
    "remark" varchar(512) DEFAULT '',
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_org_info_code" UNIQUE ("org_code")
) COMMENT '机构信息表';

CREATE TABLE IF NOT EXISTS "org_account" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "org_id" bigint NOT NULL,
    "account_name" varchar(128) DEFAULT '',
    "app_key" varchar(64) NOT NULL,
    "secret_key_cipher" varchar(512) NOT NULL,
    "key_status" tinyint NOT NULL DEFAULT 0,
    "ip_whitelist" varchar(512) DEFAULT '',
    "callback_url" varchar(256) DEFAULT '',
    "sign_algorithm" varchar(32) NOT NULL DEFAULT 'HMAC-SHA256',
    "expire_time" datetime DEFAULT NULL,
    "concurrency_limit" int DEFAULT NULL,
    "daily_limit" int DEFAULT NULL,
    "monthly_limit" int DEFAULT NULL,
    "status" tinyint NOT NULL DEFAULT 0,
    "remark" varchar(512) DEFAULT '',
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_org_account_app_key" UNIQUE ("app_key")
) COMMENT '机构账号表';
