CREATE TABLE IF NOT EXISTS "product_db_harness_smoke" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(64) NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '持久化基座冒烟表';

CREATE TABLE IF NOT EXISTS "product_info" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "product_code" varchar(32) NOT NULL,
    "name" varchar(128) NOT NULL,
    "product_type" tinyint NOT NULL DEFAULT 1,
    "auth_type" tinyint NOT NULL DEFAULT 0,
    "status" tinyint NOT NULL DEFAULT 0,
    "version" varchar(16) NOT NULL DEFAULT 'v1',
    "description" varchar(512) DEFAULT '',
    "cache_enabled" bit NOT NULL DEFAULT FALSE,
    "async_support" bit NOT NULL DEFAULT FALSE,
    "need_auth_no" bit NOT NULL DEFAULT FALSE,
    "remark" varchar(512) DEFAULT '',
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_product_info_code" UNIQUE ("product_code")
) COMMENT '产品信息表';
