CREATE DATABASE IF NOT EXISTS `apiten_system` DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS `apiten_infra` DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS `apiten_openapi` DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS `apiten_flow` DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS `apiten_adapter` DEFAULT CHARACTER SET utf8mb4;
